import pImg from "../assets/cook.png";
import pImg2 from "../assets/dove-cover.png";

export const popularProduct = [
  {
    img: pImg,
    title: "Contact",
    price: "$120",
    quantity: 2,
    total: "$240",
    text: "some thing",
    sale: true,
  },
  {
    img: pImg2,
    title: "Contact",
    price: "$120",
    quantity: 2,
    total: "$240",
    text: "some thing",
    sale: true,
  },
  {
    img: pImg,
    title: "Contact",
    price: "$120",
    quantity: 2,
    total: "$240",
    text: "some thing",
    sale: true,
  },
  {
    img: pImg2,
    title: "Contact",
    price: "$120",
    quantity: 2,
    total: "$240",
    text: "some thing",
    sale: true,
  },
  {
    img: pImg,
    title: "Contact",
    price: "$120",
    quantity: 2,
    total: "$240",
    text: "some thing",
    sale: true,
  },
  {
    img: pImg2,
    title: "Contact",
    price: "$120",
    quantity: 2,
    total: "$240",
    text: "some thing",
    sale: true,
  },
  {
    img: pImg,
    title: "Contact",
    price: "$120",
    quantity: 2,
    total: "$240",
    text: "some thing",
    sale: true,
  },
  {
    img: pImg2,
    title: "Contact",
    price: "$120",
    quantity: 2,
    total: "$240",
    text: "some thing",
    sale: true,
  },
  {
    img: pImg,
    title: "Contact",
    price: "$120",
    quantity: 2,
    total: "$240",
    text: "some thing",
    sale: true,
  },
  {
    img: pImg2,
    title: "Contact",
    price: "$120",
    quantity: 2,
    total: "$240",
    text: "some thing",
    sale: true,
  },
];
